In [1]:
# Import Dependencies
import requests
from config import api_key
import censusdata
import pandas as pd  
from sqlalchemy import create_engine
from config import remote_db_endpoint, remote_db_port
from config import remote_db_name, remote_db_user, remote_db_pwd
import numpy as np
from sqlalchemy import func
from sqlalchemy import distinct
import json
import psycopg2
import tensorflow as tf
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
cloud_engine = create_engine(f"postgresql://{remote_db_user}:{remote_db_pwd}@{remote_db_endpoint}:{remote_db_port}/{remote_db_name}")
cloud_conn = cloud_engine.connect()

ca_school_data = pd.read_sql('select * from ml_master_clean', cloud_conn)

ca_school_data.head()

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,Substance Abuse Count,Violent Count,Miscellaneous Count,School Name,School Rating,School Address,City,Grades,Students Per Teacher,District
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,317.0,50.0,52.0,The Heights Charter,7.0,"2710 Alpine Boulevard, Suite E",Alpine,K-8,15:1,Dehesa Elementary
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,317.0,50.0,52.0,Boulder Oaks Elementary,6.0,2320 Tavern Road,Alpine,1-5,24:1,Alpine Union Elementary
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,317.0,50.0,52.0,Joan MacQueen Middle,6.0,2001 Tavern Road,Alpine,6-8,20:1,Alpine Union Elementary
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,317.0,50.0,52.0,Shadow Hills Elementary,6.0,8770 Harbison Canyon Road,Alpine,K-5,20:1,Alpine Union Elementary
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,317.0,50.0,52.0,Alpine Elementary,4.0,1850 Alpine Boulevard,Alpine,1-5,20:1,Alpine Union Elementary

Four New Columns for Crime ratios are created which will standardize the count with the Zipcode population
The new columns created are 'Theft Count Ratio', 'Substance Abuse Count Ratio', 'Violent Count Ratio' and 'Miscellaneous Count Ratio'

In [3]:
ca_school_data['Theft Count Ratio'] = ca_school_data['Theft Count'] / ca_school_data['Population Total']
ca_school_data['Substance Abuse Count Ratio'] = ca_school_data['Substance Abuse Count'] / ca_school_data['Population Total']
ca_school_data['Violent Count Ratio'] = ca_school_data['Violent Count'] / ca_school_data['Population Total']
ca_school_data['Miscellaneous Count Ratio'] = ca_school_data['Miscellaneous Count'] / ca_school_data['Population Total']
ca_school_data.head(75)

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,School Rating,School Address,City,Grades,Students Per Teacher,District,Theft Count Ratio,Substance Abuse Count Ratio,Violent Count Ratio,Miscellaneous Count Ratio
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,7.0,"2710 Alpine Boulevard, Suite E",Alpine,K-8,15:1,Dehesa Elementary,0.004269,0.017129,0.002702,0.002810
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,2320 Tavern Road,Alpine,1-5,24:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,2001 Tavern Road,Alpine,6-8,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,8770 Harbison Canyon Road,Alpine,K-5,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,4.0,1850 Alpine Boulevard,Alpine,1-5,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,91915,332.0,101760.0,109750.0,0.0,101328.0,0.0,82159.0,121719.0,117525.0,...,4.0,1949 Discovery Falls Drive,Chula Vista,6-8,14:1,SBC - High Tech High,0.003226,0.000319,0.001489,0.002340
71,91916,211.0,69821.0,0.0,0.0,0.0,0.0,0.0,0.0,69955.0,...,6.0,24842 Viejas Boulevard,Descanso,K-6,21:1,Mountain Empire Unified,0.002483,0.000000,0.000000,0.000000
72,91932,896.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,6.0,650 Imperial Beach Boulevard,Imperial Beach,K-8,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126
73,91932,1585.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,4.0,505 Elm Avenue,Imperial Beach,9-12,25:1,Sweetwater Union High,0.004632,0.006402,0.004406,0.003126
74,91932,513.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,3.0,1311 10th Street,Imperial Beach,K-6,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126

Removing the Crime Actual Counts from the dataframe i.e. 
1. Theft Count
2. Substance Abuse Count
3. Violent Count
4. Miscellaneous Count

In [4]:
ca_school_data = ca_school_data.drop(labels=["Theft Count", "Substance Abuse Count","Violent Count","Miscellaneous Count"], axis=1)
ca_school_data.head(75)

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,School Rating,School Address,City,Grades,Students Per Teacher,District,Theft Count Ratio,Substance Abuse Count Ratio,Violent Count Ratio,Miscellaneous Count Ratio
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,7.0,"2710 Alpine Boulevard, Suite E",Alpine,K-8,15:1,Dehesa Elementary,0.004269,0.017129,0.002702,0.002810
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,2320 Tavern Road,Alpine,1-5,24:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,2001 Tavern Road,Alpine,6-8,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,6.0,8770 Harbison Canyon Road,Alpine,K-5,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,4.0,1850 Alpine Boulevard,Alpine,1-5,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,91915,332.0,101760.0,109750.0,0.0,101328.0,0.0,82159.0,121719.0,117525.0,...,4.0,1949 Discovery Falls Drive,Chula Vista,6-8,14:1,SBC - High Tech High,0.003226,0.000319,0.001489,0.002340
71,91916,211.0,69821.0,0.0,0.0,0.0,0.0,0.0,0.0,69955.0,...,6.0,24842 Viejas Boulevard,Descanso,K-6,21:1,Mountain Empire Unified,0.002483,0.000000,0.000000,0.000000
72,91932,896.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,6.0,650 Imperial Beach Boulevard,Imperial Beach,K-8,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126
73,91932,1585.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,4.0,505 Elm Avenue,Imperial Beach,9-12,25:1,Sweetwater Union High,0.004632,0.006402,0.004406,0.003126
74,91932,513.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,3.0,1311 10th Street,Imperial Beach,K-6,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126

Removing the following columns from the dataframe i.e. 
1. latitude
2. longitude
3. School Address
4. City
5. Grades

In [5]:
ca_school_drop = ca_school_data.drop(labels=["latitude", "longitude","School Name","School Address","City","Grades"], axis=1)
ca_school_drop.head(75)

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,Population other ratio,Population mixed ratio,Population hispanic/latino ratio,School Rating,Students Per Teacher,District,Theft Count Ratio,Substance Abuse Count Ratio,Violent Count Ratio,Miscellaneous Count Ratio
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,7.0,15:1,Dehesa Elementary,0.004269,0.017129,0.002702,0.002810
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,24:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,4.0,20:1,Alpine Union Elementary,0.004269,0.017129,0.002702,0.002810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,91915,332.0,101760.0,109750.0,0.0,101328.0,0.0,82159.0,121719.0,117525.0,...,0.010777,0.033961,0.472544,4.0,14:1,SBC - High Tech High,0.003226,0.000319,0.001489,0.002340
71,91916,211.0,69821.0,0.0,0.0,0.0,0.0,0.0,0.0,69955.0,...,0.000000,0.015518,0.120422,6.0,21:1,Mountain Empire Unified,0.002483,0.000000,0.000000,0.000000
72,91932,896.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,0.000226,0.039578,0.500998,6.0,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126
73,91932,1585.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,0.000226,0.039578,0.500998,4.0,25:1,Sweetwater Union High,0.004632,0.006402,0.004406,0.003126
74,91932,513.0,46659.0,40521.0,74773.0,41701.0,0.0,37527.0,36649.0,57344.0,...,0.000226,0.039578,0.500998,3.0,20:1,South Bay Union,0.004632,0.006402,0.004406,0.003126

In [6]:
district_type = ca_school_drop["District"].value_counts()
district_type

San Diego Unified                             212
Chula Vista Elementary                         48
Poway Unified                                  37
Vista Unified                                  28
Cajon Valley Union                             28
Escondido Union                                26
Sweetwater Union High                          25
La Mesa-Spring Valley                          23
Oceanside Unified                              23
San Marcos Unified                             18
Temecula Valley Unified                        16
Grossmont Union High                           12
National Elementary                            11
South Bay Union                                11
Ramona City Unified                            11
Mountain Empire Unified                        11
San Dieguito Union High                        10
Encinitas Union Elementary                      9
Santee                                          9
Lakeside Union Elementary                       9
Carlsbad Unified                                9
Dehesa Elementary                               8
Del Mar Union Elementary                        8
Fallbrook Union Elementary                      8
Valley Center-Pauma Unified                     7
San Ysidro Elementary                           7
Lemon Grove                                     6
SBC - High Tech High                            6
Solana Beach Elementary                         6
Escondido Union High                            6
Bonsall Unified                                 5
Jamul-Dulzura Union Elementary                  4
Julian Union Elementary                         4
Borrego Springs Unified                         4
Capistrano Unified                              4
Alpine Union Elementary                         4
Coronado Unified                                4
Fallbrook Union High                            3
Rancho Santa Fe Elementary                      2
Warner Unified                                  2
San Diego County Office of Education            2
Community Montessori District                   1
Sbe - Grossmont Secondary School District       1
Vallecitos Elementary                           1
Sbe - Thrive Public School District             1
San Pasqual Union Elementary                    1
Julian Union High                               1
Mono County Office of Education                 1
Cardiff Elementary                              1
Sbe - Audeo Charter II                          1
Sbe - Sweetwater Secondary School District      1
Name: District, dtype: int64

In [7]:
district_to_replace = list(district_type[district_type < 12].index)

# Replace in dataframe
for cls in district_to_replace:
    ca_school_drop['District'] = ca_school_drop['District'].replace(cls,"Other")
    
# Check to make sure binning was successful
ca_school_drop['District'].value_counts()

San Diego Unified          212
Other                      200
Chula Vista Elementary      48
Poway Unified               37
Vista Unified               28
Cajon Valley Union          28
Escondido Union             26
Sweetwater Union High       25
Oceanside Unified           23
La Mesa-Spring Valley       23
San Marcos Unified          18
Temecula Valley Unified     16
Grossmont Union High        12
Name: District, dtype: int64

In [8]:
# new data frame with split value columns
new = ca_school_drop["Students Per Teacher"].str.split(":", n = 1, expand = True)
  
# making separate first name column from new data frame
ca_school_drop["Students Per Teacher Count"]= new[0]
#ca_school_drop

ca_school_updated = ca_school_drop.drop(labels=["Students Per Teacher"], axis=1)
ca_school_updated

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,Population other ratio,Population mixed ratio,Population hispanic/latino ratio,School Rating,District,Theft Count Ratio,Substance Abuse Count Ratio,Violent Count Ratio,Miscellaneous Count Ratio,Students Per Teacher Count
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,7.0,Other,0.004269,0.017129,0.002702,0.00281,15
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,24
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,20
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,20
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,4.0,Other,0.004269,0.017129,0.002702,0.00281,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,92672,422.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,9.0,Other,0.000000,0.000057,0.000000,0.00000,18
692,92672,575.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,7.0,Other,0.000000,0.000057,0.000000,0.00000,25
693,92672,929.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,7.0,Other,0.000000,0.000057,0.000000,0.00000,26
694,92672,889.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,5.0,Other,0.000000,0.000057,0.000000,0.00000,27
695,92672,366.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,4.0,Other,0.000000,0.000057,0.000000,0.00000,21

In [9]:
ca_school_updated.to_csv('sd_schools_tableau.csv',index=False)

In [10]:
# Using OneHotEncoder to create the features
# Generate our categorical variable lists
ca_school_cat = list(ca_school_updated.dtypes[ca_school_updated.dtypes == "object"].index)
ca_school_cat

['District', 'Students Per Teacher Count']

In [11]:
ca_school_updated["Students Per Teacher Count"] = ca_school_updated["Students Per Teacher Count"].astype(str).astype(int)
ca_school_updated

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,Population other ratio,Population mixed ratio,Population hispanic/latino ratio,School Rating,District,Theft Count Ratio,Substance Abuse Count Ratio,Violent Count Ratio,Miscellaneous Count Ratio,Students Per Teacher Count
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,7.0,Other,0.004269,0.017129,0.002702,0.00281,15
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,24
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,20
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,6.0,Other,0.004269,0.017129,0.002702,0.00281,20
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.006754,0.012212,0.168153,4.0,Other,0.004269,0.017129,0.002702,0.00281,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,92672,422.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,9.0,Other,0.000000,0.000057,0.000000,0.00000,18
692,92672,575.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,7.0,Other,0.000000,0.000057,0.000000,0.00000,25
693,92672,929.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,7.0,Other,0.000000,0.000057,0.000000,0.00000,26
694,92672,889.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,5.0,Other,0.000000,0.000057,0.000000,0.00000,27
695,92672,366.0,77829.0,0.0,0.0,92614.0,0.0,56964.0,103520.0,80927.0,...,0.000764,0.025181,0.227365,4.0,Other,0.000000,0.000057,0.000000,0.00000,21

In [12]:
ca_school_cat = list(ca_school_updated.dtypes[ca_school_updated.dtypes == "object"].index)
ca_school_cat

['District']

In [13]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(ca_school_updated[ca_school_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(ca_school_cat)
encode_df.head(75)

,District_Cajon Valley Union,District_Chula Vista Elementary,District_Escondido Union,District_Grossmont Union High,District_La Mesa-Spring Valley,District_Oceanside Unified,District_Other,District_Poway Unified,District_San Diego Unified,District_San Marcos Unified,District_Sweetwater Union High,District_Temecula Valley Unified,District_Vista Unified
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
71,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
74,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Merge one-hot encoded features and drop the originals
ca_school_updated = ca_school_updated.merge(encode_df, left_index=True, right_index=True)
ca_school_updated = ca_school_updated.drop(labels=ca_school_cat, axis=1)
ca_school_updated.head()

,Zipcode,Total Students Enrolled,Median Household Income,Median Income BLACK/AA,Median Income INDIGENOUS PEOPLE,Median Income ASIAN,Median Income HAW/PAC ISLANDER,Median Income OTHER RACE,Median Income MIXED RACE,Median Income WHITE/NOT LATINO,...,District_Grossmont Union High,District_La Mesa-Spring Valley,District_Oceanside Unified,District_Other,District_Poway Unified,District_San Diego Unified,District_San Marcos Unified,District_Sweetwater Union High,District_Temecula Valley Unified,District_Vista Unified
0,91901,244.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,91901,333.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,91901,438.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,91901,387.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,91901,158.0,79859.0,143917.0,53750.0,78625.0,0.0,48026.0,0.0,88039.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
# Split our preprocessed data into our features and target arrays
X = ca_school_updated.drop("School Rating", axis=1).values
y = ca_school_updated["School Rating"].values.reshape(-1, 1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [51]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [52]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 500
hidden_nodes_layer2 = 400
hidden_nodes_layer3 = 300
hidden_nodes_layer4 = 200
hidden_nodes_layer5 = 100

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="sigmoid"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_40 (Dense)             (None, 400)               22000
_________________________________________________________________
dense_41 (Dense)             (None, 300)               120300
_________________________________________________________________
dense_42 (Dense)             (None, 200)               60200
_________________________________________________________________
dense_43 (Dense)             (None, 100)               20100
_________________________________________________________________
dense_44 (Dense)             (None, 1)                 101
=================================================================
Total params: 222,701
Trainable params: 222,701
Non-trainable params: 0
_________________________________________________________________

In [53]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=200)

Epoch 1/200
17/17 [==============================] - 0s 1ms/step - loss: -14.4142 - accuracy: 0.0096
Epoch 2/200
17/17 [==============================] - 0s 2ms/step - loss: -33.5264 - accuracy: 0.0096
Epoch 3/200
17/17 [==============================] - 0s 2ms/step - loss: -40.5042 - accuracy: 0.0096
Epoch 4/200
17/17 [==============================] - 0s 2ms/step - loss: -45.7021 - accuracy: 0.0096
Epoch 5/200
17/17 [==============================] - 0s 2ms/step - loss: -50.6446 - accuracy: 0.0096
Epoch 6/200
17/17 [==============================] - 0s 2ms/step - loss: -55.4817 - accuracy: 0.0096
Epoch 7/200
17/17 [==============================] - 0s 2ms/step - loss: -60.3414 - accuracy: 0.0096
Epoch 8/200
17/17 [==============================] - 0s 2ms/step - loss: -65.2698 - accuracy: 0.0096
Epoch 9/200
17/17 [==============================] - 0s 3ms/step - loss: -70.1364 - accuracy: 0.0096
Epoch 10/200
17/17 [==============================] - 0s 2ms/step - loss: -74.9852 - accuracy: 0.0096
Epoch 11/200
17/17 [==============================] - 0s 2ms/step - loss: -79.7599 - accuracy: 0.0096
Epoch 12/200
17/17 [==============================] - 0s 3ms/step - loss: -84.5620 - accuracy: 0.0096
Epoch 13/200
17/17 [==============================] - 0s 3ms/step - loss: -89.2756 - accuracy: 0.0096
Epoch 14/200
17/17 [==============================] - 0s 1ms/step - loss: -93.9756 - accuracy: 0.0096
Epoch 15/200
17/17 [==============================] - 0s 2ms/step - loss: -98.7330 - accuracy: 0.0096
Epoch 16/200
17/17 [==============================] - 0s 3ms/step - loss: -103.5994 - accuracy: 0.0096
Epoch 17/200
17/17 [==============================] - 0s 2ms/step - loss: -108.5639 - accuracy: 0.0096
Epoch 18/200
17/17 [==============================] - 0s 2ms/step - loss: -113.4809 - accuracy: 0.0096
Epoch 19/200
17/17 [==============================] - 0s 3ms/step - loss: -118.3706 - accuracy: 0.0096
Epoch 20/200
17/17 [==============================] - 0s 1ms/step - loss: -123.1959 - accuracy: 0.0096
Epoch 21/200
17/17 [==============================] - 0s 2ms/step - loss: -128.0639 - accuracy: 0.0096
Epoch 22/200
17/17 [==============================] - 0s 2ms/step - loss: -132.8457 - accuracy: 0.0096
Epoch 23/200
17/17 [==============================] - 0s 3ms/step - loss: -137.7113 - accuracy: 0.0096
Epoch 24/200
17/17 [==============================] - 0s 2ms/step - loss: -142.8139 - accuracy: 0.0096
Epoch 25/200
17/17 [==============================] - 0s 3ms/step - loss: -147.8955 - accuracy: 0.0096
Epoch 26/200
17/17 [==============================] - 0s 1ms/step - loss: -152.9191 - accuracy: 0.0096
Epoch 27/200
17/17 [==============================] - 0s 2ms/step - loss: -157.8754 - accuracy: 0.0096
Epoch 28/200
17/17 [==============================] - 0s 2ms/step - loss: -162.8482 - accuracy: 0.0096
Epoch 29/200
17/17 [==============================] - 0s 2ms/step - loss: -167.8932 - accuracy: 0.0096
Epoch 30/200
17/17 [==============================] - 0s 2ms/step - loss: -173.1826 - accuracy: 0.0096
Epoch 31/200
17/17 [==============================] - 0s 2ms/step - loss: -178.4390 - accuracy: 0.0096
Epoch 32/200
17/17 [==============================] - 0s 2ms/step - loss: -183.5780 - accuracy: 0.0096
Epoch 33/200
17/17 [==============================] - 0s 2ms/step - loss: -188.6845 - accuracy: 0.0096
Epoch 34/200
17/17 [==============================] - 0s 3ms/step - loss: -193.7453 - accuracy: 0.0096
Epoch 35/200
17/17 [==============================] - 0s 3ms/step - loss: -198.7677 - accuracy: 0.0096
Epoch 36/200
17/17 [==============================] - 0s 3ms/step - loss: -203.7677 - accuracy: 0.0096
Epoch 37/200
17/17 [==============================] - 0s 2ms/step - loss: -208.7362 - accuracy: 0.0096
Epoch 38/200
17/17 [==============================] - 0s 2ms/step - loss: -213.7601 - accuracy: 0.0096
Epoch 39/200
17/17 [==============================] - 0s 3ms/step - loss: -218.7550 - accuracy: 0.0096
Epoch 40/200
17/17 [==============================] - 0s 2ms/step - loss: -223.7437 - accuracy: 0.0096
Epoch 41/200
17/17 [==============================] - 0s 2ms/step - loss: -228.6938 - accuracy: 0.0096
Epoch 42/200
17/17 [==============================] - 0s 2ms/step - loss: -233.6824 - accuracy: 0.0096
Epoch 43/200
17/17 [==============================] - 0s 2ms/step - loss: -238.5968 - accuracy: 0.0096
Epoch 44/200
17/17 [==============================] - 0s 3ms/step - loss: -243.5388 - accuracy: 0.0096
Epoch 45/200
17/17 [==============================] - 0s 3ms/step - loss: -248.4810 - accuracy: 0.0096
Epoch 46/200
17/17 [==============================] - 0s 3ms/step - loss: -253.4111 - accuracy: 0.0096
Epoch 47/200
17/17 [==============================] - 0s 2ms/step - loss: -258.2869 - accuracy: 0.0096
Epoch 48/200
17/17 [==============================] - 0s 1ms/step - loss: -263.1946 - accuracy: 0.0096
Epoch 49/200
17/17 [==============================] - 0s 2ms/step - loss: -268.1211 - accuracy: 0.0096
Epoch 50/200
17/17 [==============================] - 0s 2ms/step - loss: -273.0283 - accuracy: 0.0096
Epoch 51/200
17/17 [==============================] - 0s 2ms/step - loss: -277.9283 - accuracy: 0.0096
Epoch 52/200
17/17 [==============================] - 0s 2ms/step - loss: -282.8116 - accuracy: 0.0096
Epoch 53/200
17/17 [==============================] - 0s 2ms/step - loss: -287.6976 - accuracy: 0.0096
Epoch 54/200
17/17 [==============================] - 0s 1ms/step - loss: -292.6182 - accuracy: 0.0096
Epoch 55/200
17/17 [==============================] - 0s 1ms/step - loss: -297.5008 - accuracy: 0.0096
Epoch 56/200
17/17 [==============================] - 0s 2ms/step - loss: -302.4454 - accuracy: 0.0096
Epoch 57/200
17/17 [==============================] - 0s 2ms/step - loss: -307.3312 - accuracy: 0.0096
Epoch 58/200
17/17 [==============================] - 0s 2ms/step - loss: -312.2422 - accuracy: 0.0096
Epoch 59/200
17/17 [==============================] - 0s 2ms/step - loss: -317.1303 - accuracy: 0.0096
Epoch 60/200
17/17 [==============================] - 0s 2ms/step - loss: -322.0381 - accuracy: 0.0096
Epoch 61/200
17/17 [==============================] - 0s 2ms/step - loss: -326.8765 - accuracy: 0.0096
Epoch 62/200
17/17 [==============================] - 0s 1ms/step - loss: -331.8116 - accuracy: 0.0096
Epoch 63/200
17/17 [==============================] - 0s 2ms/step - loss: -336.7019 - accuracy: 0.0096
Epoch 64/200
17/17 [==============================] - 0s 1ms/step - loss: -341.5403 - accuracy: 0.0096
Epoch 65/200
17/17 [==============================] - 0s 1ms/step - loss: -346.4388 - accuracy: 0.0096
Epoch 66/200
17/17 [==============================] - 0s 1ms/step - loss: -351.3234 - accuracy: 0.0096
Epoch 67/200
17/17 [==============================] - 0s 1ms/step - loss: -356.2505 - accuracy: 0.0096
Epoch 68/200
17/17 [==============================] - 0s 2ms/step - loss: -361.0797 - accuracy: 0.0096
Epoch 69/200
17/17 [==============================] - 0s 1ms/step - loss: -365.9573 - accuracy: 0.0096
Epoch 70/200
17/17 [==============================] - 0s 1ms/step - loss: -370.8214 - accuracy: 0.0096
Epoch 71/200
17/17 [==============================] - 0s 1ms/step - loss: -375.7051 - accuracy: 0.0096
Epoch 72/200
17/17 [==============================] - 0s 2ms/step - loss: -380.5814 - accuracy: 0.0096
Epoch 73/200
17/17 [==============================] - 0s 1ms/step - loss: -385.4542 - accuracy: 0.0096
Epoch 74/200
17/17 [==============================] - 0s 1ms/step - loss: -390.3324 - accuracy: 0.0096
Epoch 75/200
17/17 [==============================] - 0s 2ms/step - loss: -395.2078 - accuracy: 0.0096
Epoch 76/200
17/17 [==============================] - 0s 1ms/step - loss: -400.0515 - accuracy: 0.0096
Epoch 77/200
17/17 [==============================] - 0s 1ms/step - loss: -404.9019 - accuracy: 0.0096
Epoch 78/200
17/17 [==============================] - 0s 2ms/step - loss: -409.7321 - accuracy: 0.0096
Epoch 79/200
17/17 [==============================] - 0s 1ms/step - loss: -414.6091 - accuracy: 0.0096
Epoch 80/200
17/17 [==============================] - 0s 1ms/step - loss: -419.4694 - accuracy: 0.0096
Epoch 81/200
17/17 [==============================] - 0s 2ms/step - loss: -424.3083 - accuracy: 0.0096
Epoch 82/200
17/17 [==============================] - 0s 1ms/step - loss: -429.1574 - accuracy: 0.0096
Epoch 83/200
17/17 [==============================] - 0s 2ms/step - loss: -434.0597 - accuracy: 0.0096
Epoch 84/200
17/17 [==============================] - 0s 1ms/step - loss: -438.8666 - accuracy: 0.0096
Epoch 85/200
17/17 [==============================] - 0s 1ms/step - loss: -443.7539 - accuracy: 0.0096
Epoch 86/200
17/17 [==============================] - 0s 1ms/step - loss: -448.5714 - accuracy: 0.0096
Epoch 87/200
17/17 [==============================] - 0s 2ms/step - loss: -453.4482 - accuracy: 0.0096
Epoch 88/200
17/17 [==============================] - 0s 3ms/step - loss: -458.3291 - accuracy: 0.0096
Epoch 89/200
17/17 [==============================] - 0s 2ms/step - loss: -463.6384 - accuracy: 0.0096
Epoch 90/200
17/17 [==============================] - 0s 2ms/step - loss: -468.9325 - accuracy: 0.0096
Epoch 91/200
17/17 [==============================] - 0s 1ms/step - loss: -474.1719 - accuracy: 0.0096
Epoch 92/200
17/17 [==============================] - 0s 2ms/step - loss: -479.3301 - accuracy: 0.0096
Epoch 93/200
17/17 [==============================] - 0s 2ms/step - loss: -484.4774 - accuracy: 0.0096
Epoch 94/200
17/17 [==============================] - 0s 3ms/step - loss: -489.6006 - accuracy: 0.0096
Epoch 95/200
17/17 [==============================] - 0s 2ms/step - loss: -494.6852 - accuracy: 0.0096
Epoch 96/200
17/17 [==============================] - 0s 1ms/step - loss: -499.7366 - accuracy: 0.0096
Epoch 97/200
17/17 [==============================] - 0s 1ms/step - loss: -504.8195 - accuracy: 0.0096
Epoch 98/200
17/17 [==============================] - 0s 2ms/step - loss: -509.8499 - accuracy: 0.0096
Epoch 99/200
17/17 [==============================] - 0s 1ms/step - loss: -514.9001 - accuracy: 0.0096
Epoch 100/200
17/17 [==============================] - 0s 1ms/step - loss: -519.9490 - accuracy: 0.0096
Epoch 101/200
17/17 [==============================] - 0s 1ms/step - loss: -524.9485 - accuracy: 0.0096
Epoch 102/200
17/17 [==============================] - 0s 1ms/step - loss: -529.9122 - accuracy: 0.0096
Epoch 103/200
17/17 [==============================] - 0s 2ms/step - loss: -534.9262 - accuracy: 0.0096
Epoch 104/200
17/17 [==============================] - 0s 3ms/step - loss: -539.9328 - accuracy: 0.0096
Epoch 105/200
17/17 [==============================] - 0s 2ms/step - loss: -544.9286 - accuracy: 0.0096
Epoch 106/200
17/17 [==============================] - 0s 2ms/step - loss: -549.9131 - accuracy: 0.0096
Epoch 107/200
17/17 [==============================] - 0s 1ms/step - loss: -554.9168 - accuracy: 0.0096
Epoch 108/200
17/17 [==============================] - 0s 2ms/step - loss: -559.8494 - accuracy: 0.0096
Epoch 109/200
17/17 [==============================] - 0s 1ms/step - loss: -564.8129 - accuracy: 0.0096
Epoch 110/200
17/17 [==============================] - 0s 2ms/step - loss: -569.8203 - accuracy: 0.0096
Epoch 111/200
17/17 [==============================] - 0s 1ms/step - loss: -574.7584 - accuracy: 0.0096
Epoch 112/200
17/17 [==============================] - 0s 2ms/step - loss: -579.7615 - accuracy: 0.0096
Epoch 113/200
17/17 [==============================] - 0s 1ms/step - loss: -584.7230 - accuracy: 0.0096
Epoch 114/200
17/17 [==============================] - 0s 2ms/step - loss: -589.6592 - accuracy: 0.0096
Epoch 115/200
17/17 [==============================] - 0s 2ms/step - loss: -594.6489 - accuracy: 0.0096
Epoch 116/200
17/17 [==============================] - 0s 1ms/step - loss: -599.5571 - accuracy: 0.0096
Epoch 117/200
17/17 [==============================] - 0s 1ms/step - loss: -604.5038 - accuracy: 0.0096
Epoch 118/200
17/17 [==============================] - 0s 2ms/step - loss: -609.4820 - accuracy: 0.0096
Epoch 119/200
17/17 [==============================] - 0s 1ms/step - loss: -614.4213 - accuracy: 0.0096
Epoch 120/200
17/17 [==============================] - 0s 1ms/step - loss: -619.4452 - accuracy: 0.0096
Epoch 121/200
17/17 [==============================] - 0s 1ms/step - loss: -624.3805 - accuracy: 0.0096
Epoch 122/200
17/17 [==============================] - 0s 2ms/step - loss: -629.3516 - accuracy: 0.0096
Epoch 123/200
17/17 [==============================] - 0s 2ms/step - loss: -634.2892 - accuracy: 0.0096
Epoch 124/200
17/17 [==============================] - 0s 2ms/step - loss: -639.2905 - accuracy: 0.0096
Epoch 125/200
17/17 [==============================] - 0s 2ms/step - loss: -644.2129 - accuracy: 0.0096
Epoch 126/200
17/17 [==============================] - 0s 1ms/step - loss: -649.4514 - accuracy: 0.0096
Epoch 127/200
17/17 [==============================] - 0s 1ms/step - loss: -654.9587 - accuracy: 0.0096
Epoch 128/200
17/17 [==============================] - 0s 2ms/step - loss: -660.3498 - accuracy: 0.0096
Epoch 129/200
17/17 [==============================] - 0s 1ms/step - loss: -665.6176 - accuracy: 0.0096
Epoch 130/200
17/17 [==============================] - 0s 2ms/step - loss: -670.8679 - accuracy: 0.0096
Epoch 131/200
17/17 [==============================] - 0s 2ms/step - loss: -676.1353 - accuracy: 0.0096
Epoch 132/200
17/17 [==============================] - 0s 2ms/step - loss: -681.3124 - accuracy: 0.0096
Epoch 133/200
17/17 [==============================] - 0s 1ms/step - loss: -686.5475 - accuracy: 0.0096
Epoch 134/200
17/17 [==============================] - 0s 2ms/step - loss: -691.7235 - accuracy: 0.0096
Epoch 135/200
17/17 [==============================] - 0s 2ms/step - loss: -696.8492 - accuracy: 0.0096
Epoch 136/200
17/17 [==============================] - 0s 1ms/step - loss: -702.0246 - accuracy: 0.0096
Epoch 137/200
17/17 [==============================] - 0s 2ms/step - loss: -707.1184 - accuracy: 0.0096
Epoch 138/200
17/17 [==============================] - 0s 2ms/step - loss: -712.2141 - accuracy: 0.0096
Epoch 139/200
17/17 [==============================] - 0s 2ms/step - loss: -717.3582 - accuracy: 0.0096
Epoch 140/200
17/17 [==============================] - 0s 1ms/step - loss: -722.4703 - accuracy: 0.0096
Epoch 141/200
17/17 [==============================] - 0s 3ms/step - loss: -727.5508 - accuracy: 0.0096
Epoch 142/200
17/17 [==============================] - 0s 1ms/step - loss: -732.6975 - accuracy: 0.0096
Epoch 143/200
17/17 [==============================] - 0s 3ms/step - loss: -737.7536 - accuracy: 0.0096
Epoch 144/200
17/17 [==============================] - 0s 3ms/step - loss: -742.8478 - accuracy: 0.0096
Epoch 145/200
17/17 [==============================] - 0s 2ms/step - loss: -747.8997 - accuracy: 0.0096
Epoch 146/200
17/17 [==============================] - 0s 2ms/step - loss: -753.0120 - accuracy: 0.0096
Epoch 147/200
17/17 [==============================] - 0s 2ms/step - loss: -758.0575 - accuracy: 0.0096
Epoch 148/200
17/17 [==============================] - 0s 2ms/step - loss: -763.1276 - accuracy: 0.0096
Epoch 149/200
17/17 [==============================] - 0s 2ms/step - loss: -768.1514 - accuracy: 0.0096
Epoch 150/200
17/17 [==============================] - 0s 2ms/step - loss: -773.2204 - accuracy: 0.0096
Epoch 151/200
17/17 [==============================] - 0s 2ms/step - loss: -778.2844 - accuracy: 0.0096
Epoch 152/200
17/17 [==============================] - 0s 2ms/step - loss: -783.3251 - accuracy: 0.0096
Epoch 153/200
17/17 [==============================] - 0s 1ms/step - loss: -788.4092 - accuracy: 0.0096
Epoch 154/200
17/17 [==============================] - 0s 1ms/step - loss: -793.4532 - accuracy: 0.0096
Epoch 155/200
17/17 [==============================] - 0s 1ms/step - loss: -798.4911 - accuracy: 0.0096
Epoch 156/200
17/17 [==============================] - 0s 2ms/step - loss: -803.4809 - accuracy: 0.0096
Epoch 157/200
17/17 [==============================] - 0s 1ms/step - loss: -808.5701 - accuracy: 0.0096
Epoch 158/200
17/17 [==============================] - 0s 2ms/step - loss: -813.5883 - accuracy: 0.0096
Epoch 159/200
17/17 [==============================] - 0s 1ms/step - loss: -818.6636 - accuracy: 0.0096
Epoch 160/200
17/17 [==============================] - 0s 1ms/step - loss: -823.7709 - accuracy: 0.0096
Epoch 161/200
17/17 [==============================] - 0s 1ms/step - loss: -828.8152 - accuracy: 0.0096
Epoch 162/200
17/17 [==============================] - 0s 1ms/step - loss: -833.8329 - accuracy: 0.0096
Epoch 163/200
17/17 [==============================] - 0s 1ms/step - loss: -838.8923 - accuracy: 0.0096
Epoch 164/200
17/17 [==============================] - 0s 1ms/step - loss: -843.9316 - accuracy: 0.0096
Epoch 165/200
17/17 [==============================] - 0s 1ms/step - loss: -848.9749 - accuracy: 0.0096
Epoch 166/200
17/17 [==============================] - 0s 1ms/step - loss: -853.9904 - accuracy: 0.0096
Epoch 167/200
17/17 [==============================] - 0s 2ms/step - loss: -859.0465 - accuracy: 0.0096
Epoch 168/200
17/17 [==============================] - 0s 1ms/step - loss: -864.0883 - accuracy: 0.0096
Epoch 169/200
17/17 [==============================] - 0s 2ms/step - loss: -869.1453 - accuracy: 0.0096
Epoch 170/200
17/17 [==============================] - 0s 1ms/step - loss: -874.1804 - accuracy: 0.0096
Epoch 171/200
17/17 [==============================] - 0s 2ms/step - loss: -879.1658 - accuracy: 0.0096
Epoch 172/200
17/17 [==============================] - 0s 1ms/step - loss: -884.1851 - accuracy: 0.0096
Epoch 173/200
17/17 [==============================] - 0s 2ms/step - loss: -889.2402 - accuracy: 0.0096
Epoch 174/200
17/17 [==============================] - 0s 1ms/step - loss: -894.2466 - accuracy: 0.0096
Epoch 175/200
17/17 [==============================] - 0s 2ms/step - loss: -899.3253 - accuracy: 0.0096
Epoch 176/200
17/17 [==============================] - 0s 2ms/step - loss: -904.3170 - accuracy: 0.0096
Epoch 177/200
17/17 [==============================] - 0s 2ms/step - loss: -909.3868 - accuracy: 0.0096
Epoch 178/200
17/17 [==============================] - 0s 3ms/step - loss: -914.3878 - accuracy: 0.0096
Epoch 179/200
17/17 [==============================] - 0s 1ms/step - loss: -919.4727 - accuracy: 0.0096
Epoch 180/200
17/17 [==============================] - 0s 2ms/step - loss: -924.4842 - accuracy: 0.0096
Epoch 181/200
17/17 [==============================] - 0s 1ms/step - loss: -929.5681 - accuracy: 0.0096
Epoch 182/200
17/17 [==============================] - 0s 1ms/step - loss: -934.5704 - accuracy: 0.0096
Epoch 183/200
17/17 [==============================] - 0s 1ms/step - loss: -939.5895 - accuracy: 0.0096
Epoch 184/200
17/17 [==============================] - 0s 1ms/step - loss: -944.6727 - accuracy: 0.0096
Epoch 185/200
17/17 [==============================] - 0s 1ms/step - loss: -949.6571 - accuracy: 0.0096
Epoch 186/200
17/17 [==============================] - 0s 2ms/step - loss: -954.6556 - accuracy: 0.0096
Epoch 187/200
17/17 [==============================] - 0s 1ms/step - loss: -959.7266 - accuracy: 0.0096
Epoch 188/200
17/17 [==============================] - 0s 2ms/step - loss: -964.7081 - accuracy: 0.0096
Epoch 189/200
17/17 [==============================] - 0s 1ms/step - loss: -969.7820 - accuracy: 0.0096
Epoch 190/200
17/17 [==============================] - 0s 3ms/step - loss: -974.7391 - accuracy: 0.0096
Epoch 191/200
17/17 [==============================] - 0s 2ms/step - loss: -979.7384 - accuracy: 0.0096
Epoch 192/200
17/17 [==============================] - 0s 2ms/step - loss: -984.7794 - accuracy: 0.0096
Epoch 193/200
17/17 [==============================] - 0s 1ms/step - loss: -989.8156 - accuracy: 0.0096
Epoch 194/200

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

6/6 - 0s - loss: -1.0508e+03 - accuracy: 0.0115
Loss: -1050.7777099609375, Accuracy: 0.01149425283074379